---
# airplay handlers

  # restart the service

- name: restart shairport
  service: name=shairport state=restarted enabled=yes

  # restart the system

- name: reboot
  command: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: true

- name: waiting for come back
  local_action: wait_for host={{ inventory_hostname }} state=started
  sudo: false
