---
# master playbook

- name: sudo
  hosts: all
  sudo: no
  tasks:
    - name: os
      debug: msg="{{ ansible_distribution }} {{ ansible_distribution_release }} {{ ansible_distribution_version }}"
      tags:
        - systemcheck

- name: autohome
  hosts: autohome
  sudo: yes
  roles:
    - init
    - devenvironment
    - airplay
    - pi-wifi

- name: appserver
  hosts: appserver
  sudo: yes
  roles:
    - init

- name: wordpress
  hosts: wordpress
  sudo: yes
  vars:
    blog_names_list: "{{ blog_names.split(',') }}"
  roles:
    - init
    - devenvironment
    - wordpress

- name: sambaserver
  hosts: sambaserver
  sudo: yes
  roles:
    - init
    - devenvironment
    - samba
    - dyndns
