---
# master playbook

- name: all server
  hosts: all
  roles:
    - init
    - common
    - devenvironment

- name: appserver
  hosts: appserver
  roles:

- name: home
  hosts: home
  roles:
    - airplay
    - pi-wifi

- name: sambaserver
  hosts: sambaserver
  roles:
    - samba
    - dyndns
