---
# master playbook

- name: ping all systems
  hosts: all
  roles:
    - init
    - common
    - devenvironment
  tasks:
    - name: ping
      ping:

- name: appserver
  hosts: appserver
  roles:

- name: home
  hosts: home
  roles:
    - airplay
    - pi-wifi

- name: sambaserver
  hosts: sambaserver
  roles:
