---
# master playbook




# get os
- name: os
  hosts: all
  become: no
  tasks:
    - name: os
      debug: msg="{{ ansible_distribution }} {{ ansible_distribution_release }} {{ ansible_distribution_version }}"
      tags:
        - systemcheck

# idle server (could be used for jenkins slaves)
- name: idle
  hosts: idle
  become: yes
  roles:
    - init

# home automation
- name: autohome
  hosts: autohome
  become: yes
  roles:
    - init
    - airplay
    - pi-wifi

# application server
- name: appserver
  hosts: appserver
  become: yes
  roles:
    - init

# multi blog server with wordpress
- name: wordpress
  hosts: wordpress
  become: yes
  vars:
    blog_names_list: "{{ blog_names.split(',') }}"
  roles:
    - init
    - wordpress

# testing all roles
- name: testing
  hosts: testing
  become: yes
  vars:
    blog_names_list: "{{ blog_names.split(',') }}"
  roles:
    - init
    - airplay
    - pi-wifi
    - wordpress
