---
# master playbook


- name: home
  hosts: home
  roles:
  sudo: yes
    - init
    - devenvironment
    - airplay
    - pi-wifi



- name: appserver
  hosts: appserver
  sudo: yes
  roles:

- name: blogserver
  hosts: blogserver
  sudo: yes
  roles:
    - init
    - devenvironment
    - wordpress

- name: sambaserver
  hosts: sambaserver
  sudo: yes
  roles:
    - init
    - devenvironment
    - samba
    - dyndns
