---
# master playbook

- name: ping all systems
  hosts: all
  tasks:
  - name: ping
    ping:

- name: appserver
  hosts: appserver
  roles:
    - common
    - devenvironment

- name: roomserver
  hosts: roomserver
  roles:
    - common
    - devenvironment
    - airplay
    - pi-wifi

- name: sambaserver
  hosts: sambaserver
  roles:
    - common
    - devenvironment
