---
# master playbook

# get os
- name: os
  hosts: all
  become: no
  tasks:
    - name: os
      debug: msg="{{ ansible_distribution }} {{ ansible_distribution_release }} {{ ansible_distribution_version }}"
      notify:
        - reboot
        - waiting for come back

# home
- name: sound
  hosts: sound
  become: yes
  roles:
    - managed
    - airplay

- name: jenkins
  hosts: jenkins
  become: yes
  roles:
    - managed
