---
# master playbook


- name: home
  hosts: home
  roles:
    - init
    - common
    - devenvironment
    - airplay
    - pi-wifi

- name: appserver
  hosts: appserver
  roles:

- name: blogserver
  hosts: blogserver
  roles:
    - init
    - common
    - devenvironment
    - wordpress

- name: sambaserver
  hosts: sambaserver
  roles:
    - init
    - common
    - devenvironment
    - samba
    - dyndns
