---
# tasks for airplay




- name: install avahi deamon
  apt: name=avahi-daemon

- name: avahi
  service: name=avahi-daemon state=started enabled=yes
  tags:
    - systemcheck

- name: install git
  apt: name=git state=present

- name: install libs -> libssl-dev
  apt: name=libssl-dev state=present

- name: install libs -> libavahi-client-dev
  apt: name=libavahi-client-dev state=present

- name: install libs -> libasound2-dev
  apt: name=libasound2-dev state=present




  # use 'mkpasswd --method=SHA-512' to generate hash
- name: create shairport user
  user: name=shairport password=$6$x93fHZM89Y$Pf2LYXMuCAyaSwrK3Z85rqM62AJnVJkh1aCMVzma66XGXdzN3/irYIBDgdPZ/HRPqpcLijKbZfxTa5Pig43np0

- name: install my public key for shairport user
  authorized_key: user=shairport key="{{ lookup('file', me_key) }}" manage_dir=yes




- name: clone shairport from github
  git: repo=https://github.com/abrasive/shairport.git dest=/opt/shairport
  register: result
  notify:
    - reboot

- name: make
  command: make chdir=/opt/shairport
  when: result|changed

- name: make install
  command: make install chdir=/opt/shairport
  when: result|changed




- name: init.d copy
  command: cp /opt/shairport/scripts/debian/init.d/shairport /etc/init.d/shairport
  when: result|changed

- name: init.d permissions
  file: path=/etc/init.d/shairport mode=0755
  when: result|changed

- name: update-rc.d
  command: update-rc.d shairport defaults
  when: result|changed

- name: shairport
  service: name=shairport state=started enabled=yes
  tags:
    - systemcheck




- name: forces the USB device to become the default audio output device
  template: src=roles/airplay/files/alsa-base.conf.j2 dest=/etc/modprobe.d/alsa-base.conf owner=0 group=0 mode=0644 backup=yes
  notify:
    - reboot
