---
# tasks for airplay

- name: install libs -> libssl-dev
  apt: name=libssl-dev state=present
  tags:
    - deploy


- name: install libs -> libavahi-client-dev
  apt: name=libavahi-client-dev state=present
  tags:
    - deploy

- name: install libs -> libasound2-dev
  apt: name=libasound2-dev state=present
  tags:
    - deploy




  # use 'mkpasswd --method=SHA-512' to generate hash
- name: create shairport user
  user: name=shairport password={{ unix_default_password_hash }}
  tags:
    - deploy

- name: install my public key for shairport user
  authorized_key: user=shairport key="{{ lookup('file', me_key) }}" manage_dir=yes
  tags:
    - deploy




# install shairport
- name: clone shairport from github
  git: repo=https://github.com/abrasive/shairport.git dest=/opt/shairport
  register: clone_shairport
  notify:
    - reboot
    - waiting for come back
  tags:
    - deploy

- name: make
  command: make chdir=/opt/shairport
  when: clone_shairport|changed
  tags:
    - deploy

- name: make install
  command: make install chdir=/opt/shairport
  when: clone_shairport|changed
  tags:
    - deploy




- name: init.d copy
  command: cp /opt/shairport/scripts/debian/init.d/shairport /etc/init.d/shairport
  when: clone_shairport|changed
  tags:
    - deploy

- name: init.d permissions
  file: path=/etc/init.d/shairport mode=0755
  when: clone_shairport|changed
  tags:
    - deploy

- name: update-rc.d
  command: update-rc.d shairport defaults
  when: clone_shairport|changed
  tags:
    - deploy

- name: change AP Name
  lineinfile: dest=/etc/init.d/shairport regexp=^AP_NAME= line=AP_NAME={{ host_name | capitalize }}
  notify:
    - reboot
    - waiting for come back
  tags:
    - deploy

- name: shairport
  service: name=shairport state=started enabled=yes
  tags:
    - deploy
    - service



- name: forces the USB device to become the default audio output device
  template: src=alsa-base.conf.j2 dest=/etc/modprobe.d/alsa-base.conf owner=0 group=0 mode=0644 backup=yes
  notify:
    - reboot
    - waiting for come back
  tags:
    - deploy
