---
# tasks for devEnvironment

# install most important packages

- name: install tools
  apt: name={{ item }} state=latest
  with_items:
    - zsh
    - vim
    - git
    - nmap

- name: switch to zsh
  command: chsh -s /bin/zsh "{{ ansible_ssh_user }}"
  changed_when: False





# get devEnvironment from github

- name: clone devEnvironment from github
  git: repo=https://github.com/cowboycod3r/devEnvironment.git dest=/opt/devEnvironment version=debian
  register: result

- name: create sym links for remote user
  shell: ./create-links.sh chdir=/opt/devEnvironment
  when: result|changed
