---
# dyndns handlers

- name: restart ddclient
  service: name=ddclient state=restarted enabled=yes

- name: reboot
  command: reboot
  async: 20
  poll: 0
  ignore_errors: true

- name: waiting for come back
  local_action: wait_for host={{ inventory_hostname }} port=22 state=started  timeout=120
  become: no
