---
# common handlers

- name: restart nginx
  service: name=nginx state=restarted enabled=yes

- name: restart fpm
  service: name=php5-fpm state=restarted enabled=yes

- name: restart mysql
  service: name=mysql state=restarted enabled=yes

- name: reboot
  command: reboot
  async: 20
  poll: 0
  ignore_errors: true

- name: waiting for come back
  local_action: wait_for host={{ inventory_hostname }} state=started
  sudo: false
