---
# common handlers

- name: restart sshd
  service: name=ssh state=restarted enabled=yes

- name: reboot
  command: reboot
  async: 20
  poll: 0
  ignore_errors: true

- name: waiting for come back
  local_action: wait_for host={{ inventory_hostname }} state=started
  sudo: false
