---
# tasks for pi wifi
- name: wifi dir
  file: path=/etc/wpa_supplicant state=directory
  tags:
    - deploy

- name: wifi config file
  template: src=wpa_supplicant.conf.j2 dest=/etc/wpa_supplicant/wpa_supplicant.conf backup=yes
  notify:
    - reboot
    - waiting for come back
  tags:
    - deploy
