---
# pi wifi handlers

  # restart the system

- name: reboot
  command: reboot
  async: 20
  poll: 0
  ignore_errors: true

- name: waiting for come back
  local_action: wait_for host={{ inventory_hostname }} port=22 state=started  timeout=120
  sudo: false

- name: ping
  ping:
