---
# tasks for init




# hostname

- name: set the hostname
  hostname: name="{{ host_name }}"
  notify:
    - reboot
    - waiting for come back

- name: update hosts file
  lineinfile: dest=/etc/hosts regexp="^127.0.1.1" line="127.0.1.1\t{{ host_name }}"
  notify:
    - reboot
    - waiting for come back




# system update

- name: update all system components
  apt: update_cache=yes upgrade=yes




# install most important packages

- name: install avahi deamon to become visible in the network
  apt: name=avahi-daemon

- name: update the avahi configuration for ssh
  template: src=ssh.service.j2 dest=/etc/avahi/services/ssh.service backup=yes
  notify:
    - restart avahi

- name: update the avahi configuration for sftp
  template: src=sftp.service.j2 dest=/etc/avahi/services/sftp.service backup=yes
  notify:
    - restart avahi

- name: avahi service
  service: name=avahi-daemon state=started enabled=yes
  tags:
    - systemcheck





# create users and provide public key

  # use mkpasswd --method=SHA-512 to generate hash
- name: create me as new user
  user: name={{ me }} shell=/bin/zsh password=$6$x93fHZM89Y$Pf2LYXMuCAyaSwrK3Z85rqM62AJnVJkh1aCMVzma66XGXdzN3/irYIBDgdPZ/HRPqpcLijKbZfxTa5Pig43np0

- name: check the owner of my home dir
  file: path=/home/{{ me }} owner={{ me }} group={{ me }} recurse=yes

- name: install my public key for me
  authorized_key: user={{ me }} key="{{ lookup('file', me_key) }}" manage_dir=yes

- name: add me to sudoers
  lineinfile: dest=/etc/sudoers state=present regexp="^{{ me }}" line="{{ me }}   ALL=(ALL:ALL) ALL" insertafter="^root"




# provide public keys for remote user

- name: provide public key for the current remote user
  authorized_key: user="{{ ansible_ssh_user }}" key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}" manage_dir=yes

- name: provide my public key for the remote user too
  authorized_key: user="{{ ansible_ssh_user }}" key="{{ lookup('file', me_key) }}" manage_dir=yes




# update sshd configuration

- name: update the sshd configuration file to avoid login with password
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config backup=yes owner=0 group=0 mode=0644
  notify:
    - reboot
    - waiting for come back


